-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config9_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_4_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_5_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_6_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_7_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_relu_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_relu_config9_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv15_0 : STD_LOGIC_VECTOR (14 downto 0) := "000000000000000";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal icmp_ln45_fu_100_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln43_6_fu_96_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_fu_106_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_1_fu_118_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln43_5_fu_92_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_1_fu_124_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_2_fu_136_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln43_4_fu_88_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_2_fu_142_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_3_fu_154_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln43_3_fu_84_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_3_fu_160_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_4_fu_172_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln43_2_fu_80_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_4_fu_178_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_5_fu_190_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln43_1_fu_76_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_5_fu_196_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal icmp_ln45_6_fu_208_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln43_fu_72_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal datareg_6_fu_214_p3 : STD_LOGIC_VECTOR (14 downto 0);
    signal zext_ln45_fu_114_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_1_fu_132_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_2_fu_150_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_3_fu_168_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_4_fu_186_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_5_fu_204_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal zext_ln45_6_fu_222_p1 : STD_LOGIC_VECTOR (15 downto 0);


begin



    ap_ready <= ap_const_logic_1;
    ap_return_0 <= zext_ln45_fu_114_p1;
    ap_return_1 <= zext_ln45_1_fu_132_p1;
    ap_return_2 <= zext_ln45_2_fu_150_p1;
    ap_return_3 <= zext_ln45_3_fu_168_p1;
    ap_return_4 <= zext_ln45_4_fu_186_p1;
    ap_return_5 <= zext_ln45_5_fu_204_p1;
    ap_return_6 <= zext_ln45_6_fu_222_p1;
    datareg_1_fu_124_p3 <= 
        trunc_ln43_5_fu_92_p1 when (icmp_ln45_1_fu_118_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_2_fu_142_p3 <= 
        trunc_ln43_4_fu_88_p1 when (icmp_ln45_2_fu_136_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_3_fu_160_p3 <= 
        trunc_ln43_3_fu_84_p1 when (icmp_ln45_3_fu_154_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_4_fu_178_p3 <= 
        trunc_ln43_2_fu_80_p1 when (icmp_ln45_4_fu_172_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_5_fu_196_p3 <= 
        trunc_ln43_1_fu_76_p1 when (icmp_ln45_5_fu_190_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_6_fu_214_p3 <= 
        trunc_ln43_fu_72_p1 when (icmp_ln45_6_fu_208_p2(0) = '1') else 
        ap_const_lv15_0;
    datareg_fu_106_p3 <= 
        trunc_ln43_6_fu_96_p1 when (icmp_ln45_fu_100_p2(0) = '1') else 
        ap_const_lv15_0;
    icmp_ln45_1_fu_118_p2 <= "1" when (signed(data_1_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_2_fu_136_p2 <= "1" when (signed(data_3_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_3_fu_154_p2 <= "1" when (signed(data_4_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_4_fu_172_p2 <= "1" when (signed(data_5_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_5_fu_190_p2 <= "1" when (signed(data_6_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_6_fu_208_p2 <= "1" when (signed(data_7_val) > signed(ap_const_lv16_0)) else "0";
    icmp_ln45_fu_100_p2 <= "1" when (signed(data_0_val) > signed(ap_const_lv16_0)) else "0";
    trunc_ln43_1_fu_76_p1 <= data_6_val(15 - 1 downto 0);
    trunc_ln43_2_fu_80_p1 <= data_5_val(15 - 1 downto 0);
    trunc_ln43_3_fu_84_p1 <= data_4_val(15 - 1 downto 0);
    trunc_ln43_4_fu_88_p1 <= data_3_val(15 - 1 downto 0);
    trunc_ln43_5_fu_92_p1 <= data_1_val(15 - 1 downto 0);
    trunc_ln43_6_fu_96_p1 <= data_0_val(15 - 1 downto 0);
    trunc_ln43_fu_72_p1 <= data_7_val(15 - 1 downto 0);
    zext_ln45_1_fu_132_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_1_fu_124_p3),16));
    zext_ln45_2_fu_150_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_2_fu_142_p3),16));
    zext_ln45_3_fu_168_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_3_fu_160_p3),16));
    zext_ln45_4_fu_186_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_4_fu_178_p3),16));
    zext_ln45_5_fu_204_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_5_fu_196_p3),16));
    zext_ln45_6_fu_222_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_6_fu_214_p3),16));
    zext_ln45_fu_114_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(datareg_fu_106_p3),16));
end behav;
