-- ==============================================================
-- Generated by Vitis HLS v2023.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s is
port (
    ap_ready : OUT STD_LOGIC;
    data_0_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_1_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_2_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_3_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_4_val : IN STD_LOGIC_VECTOR (15 downto 0);
    data_5_val : IN STD_LOGIC_VECTOR (15 downto 0);
    ap_return_0 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_1 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_2 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_3 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_4 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_5 : OUT STD_LOGIC_VECTOR (15 downto 0);
    ap_return_6 : OUT STD_LOGIC_VECTOR (15 downto 0) );
end;


architecture behav of myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv26_3FFFDE6 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110111100110";
    constant ap_const_lv26_3FFFE4B : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111001001011";
    constant ap_const_lv26_3FFFDE4 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110111100100";
    constant ap_const_lv26_3FFFDF2 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110111110010";
    constant ap_const_lv26_23A : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001000111010";
    constant ap_const_lv26_239 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001000111001";
    constant ap_const_lv26_3FFFE35 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111000110101";
    constant ap_const_lv26_262 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001001100010";
    constant ap_const_lv26_258 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001001011000";
    constant ap_const_lv26_235 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001000110101";
    constant ap_const_lv26_3FFFE36 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111111000110110";
    constant ap_const_lv26_3FFFDEB : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110111101011";
    constant ap_const_lv26_3FFFD91 : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110110010001";
    constant ap_const_lv26_3FFFDAC : STD_LOGIC_VECTOR (25 downto 0) := "11111111111111110110101100";
    constant ap_const_lv26_20B : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000001000001011";
    constant ap_const_lv26_1C8 : STD_LOGIC_VECTOR (25 downto 0) := "00000000000000000111001000";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv32_19 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011001";
    constant ap_const_lv16_1 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000001";
    constant ap_const_lv16_FFF4 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111110100";
    constant ap_const_lv16_4 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000100";
    constant ap_const_lv16_13 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000010011";
    constant ap_const_lv16_2 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000010";
    constant ap_const_lv16_FFF9 : STD_LOGIC_VECTOR (15 downto 0) := "1111111111111001";
    constant ap_const_logic_0 : STD_LOGIC := '0';

attribute shreg_extract : string;
    signal mul_ln42_11_fu_116_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln73_1_fu_1443_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_11_fu_116_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_fu_117_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_fu_1269_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln73_fu_117_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln42_6_fu_118_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln73_fu_1369_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_6_fu_118_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_2_fu_119_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_fu_1295_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_2_fu_119_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_3_fu_120_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_3_fu_120_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_fu_121_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_fu_121_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_2_fu_122_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln42_1_fu_1343_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln73_2_fu_122_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln42_7_fu_123_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln70_1_fu_1395_p1 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_7_fu_123_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_1_fu_124_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_1_fu_124_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_5_fu_125_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_5_fu_125_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_3_fu_126_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln73_3_fu_126_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln42_8_fu_127_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_8_fu_127_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_4_fu_128_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_4_fu_128_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_9_fu_129_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_9_fu_129_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln42_10_fu_130_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln42_10_fu_130_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln73_1_fu_131_p0 : STD_LOGIC_VECTOR (15 downto 0);
    signal mul_ln73_1_fu_131_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_ln73_fu_117_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_fu_121_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln73_1_fu_131_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_1_fu_124_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_2_fu_119_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_3_fu_120_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln73_2_fu_122_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_4_fu_128_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_5_fu_125_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_6_fu_118_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln73_3_fu_126_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_7_fu_123_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_8_fu_127_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_9_fu_129_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_10_fu_130_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal mul_ln42_11_fu_116_p2 : STD_LOGIC_VECTOR (25 downto 0);
    signal trunc_ln42_8_fu_1375_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_s_fu_1403_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_2_fu_1303_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln_fu_1275_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_6_fu_1349_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_10_fu_1413_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_3_fu_1487_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_2_fu_1481_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_11_fu_1423_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_5_fu_1499_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_1_fu_1285_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_4_fu_1323_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_7_fu_1359_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_12_fu_1433_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_8_fu_1517_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_7_fu_1511_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_3_fu_1313_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_9_fu_1385_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_13_fu_1449_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_11_fu_1535_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_10_fu_1529_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_14_fu_1459_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_13_fu_1547_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln42_5_fu_1333_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_1_fu_1475_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_4_fu_1493_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_6_fu_1505_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_fu_1469_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_12_fu_1541_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_9_fu_1523_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal add_ln58_14_fu_1553_p2 : STD_LOGIC_VECTOR (15 downto 0);

    component myproject_mul_16s_11s_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_10s_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_11ns_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (10 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;


    component myproject_mul_16s_10ns_26_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (15 downto 0);
        din1 : IN STD_LOGIC_VECTOR (9 downto 0);
        dout : OUT STD_LOGIC_VECTOR (25 downto 0) );
    end component;



begin
    mul_16s_11s_26_1_1_U47 : component myproject_mul_16s_11s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_11_fu_116_p0,
        din1 => mul_ln42_11_fu_116_p1,
        dout => mul_ln42_11_fu_116_p2);

    mul_16s_10s_26_1_1_U48 : component myproject_mul_16s_10s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln73_fu_117_p0,
        din1 => mul_ln73_fu_117_p1,
        dout => mul_ln73_fu_117_p2);

    mul_16s_11s_26_1_1_U49 : component myproject_mul_16s_11s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_6_fu_118_p0,
        din1 => mul_ln42_6_fu_118_p1,
        dout => mul_ln42_6_fu_118_p2);

    mul_16s_11s_26_1_1_U50 : component myproject_mul_16s_11s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_2_fu_119_p0,
        din1 => mul_ln42_2_fu_119_p1,
        dout => mul_ln42_2_fu_119_p2);

    mul_16s_11ns_26_1_1_U51 : component myproject_mul_16s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_3_fu_120_p0,
        din1 => mul_ln42_3_fu_120_p1,
        dout => mul_ln42_3_fu_120_p2);

    mul_16s_11ns_26_1_1_U52 : component myproject_mul_16s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_fu_121_p0,
        din1 => mul_ln42_fu_121_p1,
        dout => mul_ln42_fu_121_p2);

    mul_16s_10s_26_1_1_U53 : component myproject_mul_16s_10s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln73_2_fu_122_p0,
        din1 => mul_ln73_2_fu_122_p1,
        dout => mul_ln73_2_fu_122_p2);

    mul_16s_11ns_26_1_1_U54 : component myproject_mul_16s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_7_fu_123_p0,
        din1 => mul_ln42_7_fu_123_p1,
        dout => mul_ln42_7_fu_123_p2);

    mul_16s_11ns_26_1_1_U55 : component myproject_mul_16s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_1_fu_124_p0,
        din1 => mul_ln42_1_fu_124_p1,
        dout => mul_ln42_1_fu_124_p2);

    mul_16s_11ns_26_1_1_U56 : component myproject_mul_16s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_5_fu_125_p0,
        din1 => mul_ln42_5_fu_125_p1,
        dout => mul_ln42_5_fu_125_p2);

    mul_16s_10s_26_1_1_U57 : component myproject_mul_16s_10s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln73_3_fu_126_p0,
        din1 => mul_ln73_3_fu_126_p1,
        dout => mul_ln73_3_fu_126_p2);

    mul_16s_11s_26_1_1_U58 : component myproject_mul_16s_11s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_8_fu_127_p0,
        din1 => mul_ln42_8_fu_127_p1,
        dout => mul_ln42_8_fu_127_p2);

    mul_16s_11s_26_1_1_U59 : component myproject_mul_16s_11s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_4_fu_128_p0,
        din1 => mul_ln42_4_fu_128_p1,
        dout => mul_ln42_4_fu_128_p2);

    mul_16s_11s_26_1_1_U60 : component myproject_mul_16s_11s_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_9_fu_129_p0,
        din1 => mul_ln42_9_fu_129_p1,
        dout => mul_ln42_9_fu_129_p2);

    mul_16s_11ns_26_1_1_U61 : component myproject_mul_16s_11ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 11,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln42_10_fu_130_p0,
        din1 => mul_ln42_10_fu_130_p1,
        dout => mul_ln42_10_fu_130_p2);

    mul_16s_10ns_26_1_1_U62 : component myproject_mul_16s_10ns_26_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 16,
        din1_WIDTH => 10,
        dout_WIDTH => 26)
    port map (
        din0 => mul_ln73_1_fu_131_p0,
        din1 => mul_ln73_1_fu_131_p1,
        dout => mul_ln73_1_fu_131_p2);




    add_ln58_10_fu_1529_p2 <= std_logic_vector(unsigned(trunc_ln42_3_fu_1313_p4) + unsigned(trunc_ln42_9_fu_1385_p4));
    add_ln58_11_fu_1535_p2 <= std_logic_vector(unsigned(trunc_ln42_13_fu_1449_p4) + unsigned(ap_const_lv16_2));
    add_ln58_12_fu_1541_p2 <= std_logic_vector(unsigned(add_ln58_11_fu_1535_p2) + unsigned(add_ln58_10_fu_1529_p2));
    add_ln58_13_fu_1547_p2 <= std_logic_vector(unsigned(trunc_ln42_14_fu_1459_p4) + unsigned(ap_const_lv16_FFF9));
    add_ln58_14_fu_1553_p2 <= std_logic_vector(unsigned(add_ln58_13_fu_1547_p2) + unsigned(trunc_ln42_5_fu_1333_p4));
    add_ln58_1_fu_1475_p2 <= std_logic_vector(unsigned(trunc_ln42_s_fu_1403_p4) + unsigned(ap_const_lv16_FFF4));
    add_ln58_2_fu_1481_p2 <= std_logic_vector(unsigned(trunc_ln42_2_fu_1303_p4) + unsigned(trunc_ln_fu_1275_p4));
    add_ln58_3_fu_1487_p2 <= std_logic_vector(unsigned(trunc_ln42_6_fu_1349_p4) + unsigned(trunc_ln42_10_fu_1413_p4));
    add_ln58_4_fu_1493_p2 <= std_logic_vector(unsigned(add_ln58_3_fu_1487_p2) + unsigned(add_ln58_2_fu_1481_p2));
    add_ln58_5_fu_1499_p2 <= std_logic_vector(unsigned(trunc_ln42_11_fu_1423_p4) + unsigned(ap_const_lv16_4));
    add_ln58_6_fu_1505_p2 <= std_logic_vector(unsigned(add_ln58_5_fu_1499_p2) + unsigned(trunc_ln42_1_fu_1285_p4));
    add_ln58_7_fu_1511_p2 <= std_logic_vector(unsigned(trunc_ln42_4_fu_1323_p4) + unsigned(trunc_ln42_7_fu_1359_p4));
    add_ln58_8_fu_1517_p2 <= std_logic_vector(unsigned(trunc_ln42_12_fu_1433_p4) + unsigned(ap_const_lv16_13));
    add_ln58_9_fu_1523_p2 <= std_logic_vector(unsigned(add_ln58_8_fu_1517_p2) + unsigned(add_ln58_7_fu_1511_p2));
    add_ln58_fu_1469_p2 <= std_logic_vector(unsigned(trunc_ln42_8_fu_1375_p4) + unsigned(ap_const_lv16_1));
    ap_ready <= ap_const_logic_1;
    ap_return_0 <= add_ln58_1_fu_1475_p2;
    ap_return_1 <= add_ln58_4_fu_1493_p2;
    ap_return_2 <= add_ln58_6_fu_1505_p2;
    ap_return_3 <= add_ln58_fu_1469_p2;
    ap_return_4 <= add_ln58_12_fu_1541_p2;
    ap_return_5 <= add_ln58_9_fu_1523_p2;
    ap_return_6 <= add_ln58_14_fu_1553_p2;
    mul_ln42_10_fu_130_p0 <= sext_ln73_1_fu_1443_p1(16 - 1 downto 0);
    mul_ln42_10_fu_130_p1 <= ap_const_lv26_20B(11 - 1 downto 0);
    mul_ln42_11_fu_116_p0 <= sext_ln73_1_fu_1443_p1(16 - 1 downto 0);
    mul_ln42_11_fu_116_p1 <= ap_const_lv26_3FFFDE6(11 - 1 downto 0);
    mul_ln42_1_fu_124_p0 <= sext_ln70_fu_1295_p1(16 - 1 downto 0);
    mul_ln42_1_fu_124_p1 <= ap_const_lv26_258(11 - 1 downto 0);
    mul_ln42_2_fu_119_p0 <= sext_ln70_fu_1295_p1(16 - 1 downto 0);
    mul_ln42_2_fu_119_p1 <= ap_const_lv26_3FFFDF2(11 - 1 downto 0);
    mul_ln42_3_fu_120_p0 <= sext_ln70_fu_1295_p1(16 - 1 downto 0);
    mul_ln42_3_fu_120_p1 <= ap_const_lv26_23A(11 - 1 downto 0);
    mul_ln42_4_fu_128_p0 <= sext_ln42_1_fu_1343_p1(16 - 1 downto 0);
    mul_ln42_4_fu_128_p1 <= ap_const_lv26_3FFFD91(11 - 1 downto 0);
    mul_ln42_5_fu_125_p0 <= sext_ln73_fu_1369_p1(16 - 1 downto 0);
    mul_ln42_5_fu_125_p1 <= ap_const_lv26_235(11 - 1 downto 0);
    mul_ln42_6_fu_118_p0 <= sext_ln73_fu_1369_p1(16 - 1 downto 0);
    mul_ln42_6_fu_118_p1 <= ap_const_lv26_3FFFDE4(11 - 1 downto 0);
    mul_ln42_7_fu_123_p0 <= sext_ln70_1_fu_1395_p1(16 - 1 downto 0);
    mul_ln42_7_fu_123_p1 <= ap_const_lv26_262(11 - 1 downto 0);
    mul_ln42_8_fu_127_p0 <= sext_ln70_1_fu_1395_p1(16 - 1 downto 0);
    mul_ln42_8_fu_127_p1 <= ap_const_lv26_3FFFDEB(11 - 1 downto 0);
    mul_ln42_9_fu_129_p0 <= sext_ln70_1_fu_1395_p1(16 - 1 downto 0);
    mul_ln42_9_fu_129_p1 <= ap_const_lv26_3FFFDAC(11 - 1 downto 0);
    mul_ln42_fu_121_p0 <= sext_ln42_fu_1269_p1(16 - 1 downto 0);
    mul_ln42_fu_121_p1 <= ap_const_lv26_239(11 - 1 downto 0);
    mul_ln73_1_fu_131_p0 <= sext_ln70_fu_1295_p1(16 - 1 downto 0);
    mul_ln73_1_fu_131_p1 <= ap_const_lv26_1C8(10 - 1 downto 0);
    mul_ln73_2_fu_122_p0 <= sext_ln42_1_fu_1343_p1(16 - 1 downto 0);
    mul_ln73_2_fu_122_p1 <= ap_const_lv26_3FFFE35(10 - 1 downto 0);
    mul_ln73_3_fu_126_p0 <= sext_ln70_1_fu_1395_p1(16 - 1 downto 0);
    mul_ln73_3_fu_126_p1 <= ap_const_lv26_3FFFE36(10 - 1 downto 0);
    mul_ln73_fu_117_p0 <= sext_ln42_fu_1269_p1(16 - 1 downto 0);
    mul_ln73_fu_117_p1 <= ap_const_lv26_3FFFE4B(10 - 1 downto 0);
        sext_ln42_1_fu_1343_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_2_val),26));

        sext_ln42_fu_1269_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_0_val),26));

        sext_ln70_1_fu_1395_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_4_val),26));

        sext_ln70_fu_1295_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_1_val),26));

        sext_ln73_1_fu_1443_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_5_val),26));

        sext_ln73_fu_1369_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(data_3_val),26));

    trunc_ln42_10_fu_1413_p4 <= mul_ln42_7_fu_123_p2(25 downto 10);
    trunc_ln42_11_fu_1423_p4 <= mul_ln42_8_fu_127_p2(25 downto 10);
    trunc_ln42_12_fu_1433_p4 <= mul_ln42_9_fu_129_p2(25 downto 10);
    trunc_ln42_13_fu_1449_p4 <= mul_ln42_10_fu_130_p2(25 downto 10);
    trunc_ln42_14_fu_1459_p4 <= mul_ln42_11_fu_116_p2(25 downto 10);
    trunc_ln42_1_fu_1285_p4 <= mul_ln42_fu_121_p2(25 downto 10);
    trunc_ln42_2_fu_1303_p4 <= mul_ln73_1_fu_131_p2(25 downto 10);
    trunc_ln42_3_fu_1313_p4 <= mul_ln42_1_fu_124_p2(25 downto 10);
    trunc_ln42_4_fu_1323_p4 <= mul_ln42_2_fu_119_p2(25 downto 10);
    trunc_ln42_5_fu_1333_p4 <= mul_ln42_3_fu_120_p2(25 downto 10);
    trunc_ln42_6_fu_1349_p4 <= mul_ln73_2_fu_122_p2(25 downto 10);
    trunc_ln42_7_fu_1359_p4 <= mul_ln42_4_fu_128_p2(25 downto 10);
    trunc_ln42_8_fu_1375_p4 <= mul_ln42_5_fu_125_p2(25 downto 10);
    trunc_ln42_9_fu_1385_p4 <= mul_ln42_6_fu_118_p2(25 downto 10);
    trunc_ln42_s_fu_1403_p4 <= mul_ln73_3_fu_126_p2(25 downto 10);
    trunc_ln_fu_1275_p4 <= mul_ln73_fu_117_p2(25 downto 10);
end behav;
