Backend: Vitis
ClockPeriod: 5
HLSConfig:
  LayerName:
    dense_node_1:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    dense_node_1_input:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense_node_1_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense_node_2:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    dense_node_2_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense_node_3:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    dense_node_3_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense_node_4:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    dense_node_4_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense_node_out:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    dense_node_out_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'model_NN/node_network/keras_model.h5'
OutputDir: model_NN/node_network
OutputPredictions: null
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: 1Da2e5DE
