Backend: Vitis
ClockPeriod: 5
HLSConfig:
  LayerName:
    dense_in_1:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    dense_in_1_input:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense_in_1_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense_in_2:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    dense_in_2_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense_in_3:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    dense_in_3_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
    dense_in_out:
      Precision:
        bias: fixed<16,6>
        result: fixed<16,6>
        weight: fixed<16,6>
      Trace: false
    dense_in_out_relu:
      Precision:
        result: fixed<16,6>
      Trace: false
  Model:
    BramFactor: 1000000000
    Precision: fixed<16,6>
    ReuseFactor: 1
    Strategy: Latency
    TraceOutput: false
IOType: io_parallel
InputData: null
KerasModel: !keras_model 'model_NN/input_network/keras_model.h5'
OutputDir: model_NN/input_network
OutputPredictions: null
Part: xcu250-figd2104-2L-e
ProjectName: myproject
Stamp: A329d56c
