// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5
);


output   ap_ready;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;

wire  signed [15:0] mul_ln42_17_fu_108_p0;
wire  signed [25:0] sext_ln73_4_fu_907_p1;
wire  signed [10:0] mul_ln42_17_fu_108_p1;
wire  signed [15:0] mul_ln42_13_fu_109_p0;
wire  signed [25:0] sext_ln73_fu_779_p1;
wire   [10:0] mul_ln42_13_fu_109_p1;
wire  signed [10:0] mul_ln42_15_fu_114_p1;
wire   [10:0] mul_ln42_fu_115_p1;
wire  signed [15:0] mul_ln42_18_fu_117_p0;
wire   [10:0] mul_ln42_18_fu_117_p1;
wire  signed [15:0] mul_ln42_14_fu_119_p0;
wire   [10:0] mul_ln42_14_fu_119_p1;
wire  signed [9:0] mul_ln73_fu_120_p1;
wire  signed [15:0] mul_ln42_12_fu_122_p0;
wire  signed [10:0] mul_ln42_12_fu_122_p1;
wire   [10:0] mul_ln42_16_fu_123_p1;
wire   [25:0] mul_ln42_fu_115_p2;
wire   [25:0] mul_ln42_12_fu_122_p2;
wire   [25:0] mul_ln42_13_fu_109_p2;
wire   [25:0] mul_ln42_14_fu_119_p2;
wire  signed [15:0] shl_ln_fu_821_p1;
wire   [24:0] shl_ln_fu_821_p3;
wire  signed [25:0] sext_ln73_2_fu_829_p1;
wire  signed [15:0] shl_ln73_1_fu_839_p1;
wire   [20:0] shl_ln73_1_fu_839_p3;
wire   [25:0] sub_ln73_fu_833_p2;
wire  signed [25:0] sext_ln73_3_fu_847_p1;
wire   [25:0] sub_ln73_1_fu_851_p2;
wire   [25:0] mul_ln73_fu_120_p2;
wire   [25:0] mul_ln42_15_fu_114_p2;
wire   [25:0] mul_ln42_16_fu_123_p2;
wire   [25:0] mul_ln42_17_fu_108_p2;
wire   [25:0] mul_ln42_18_fu_117_p2;
wire   [15:0] trunc_ln42_15_fu_796_p4;
wire   [15:0] trunc_ln42_18_fu_867_p4;
wire   [15:0] trunc_ln42_s_fu_786_p4;
wire   [15:0] trunc_ln42_20_fu_897_p4;
wire   [15:0] trunc_ln42_22_fu_923_p4;
wire   [15:0] add_ln58_17_fu_951_p2;
wire   [15:0] trunc_ln42_17_fu_857_p4;
wire   [15:0] trunc_ln_fu_769_p4;
wire   [15:0] trunc_ln42_21_fu_913_p4;
wire   [15:0] trunc_ln42_16_fu_806_p4;
wire   [15:0] trunc_ln42_19_fu_882_p4;
wire   [15:0] add_ln58_20_fu_969_p2;
wire   [15:0] add_ln58_19_fu_963_p2;
wire   [15:0] add_ln58_18_fu_957_p2;
wire   [15:0] add_ln58_15_fu_939_p2;
wire   [15:0] add_ln58_16_fu_945_p2;
wire   [15:0] add_ln58_fu_933_p2;
wire   [15:0] add_ln58_21_fu_975_p2;

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U26(
    .din0(mul_ln42_17_fu_108_p0),
    .din1(mul_ln42_17_fu_108_p1),
    .dout(mul_ln42_17_fu_108_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U27(
    .din0(mul_ln42_13_fu_109_p0),
    .din1(mul_ln42_13_fu_109_p1),
    .dout(mul_ln42_13_fu_109_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U28(
    .din0(data_3_val),
    .din1(mul_ln42_15_fu_114_p1),
    .dout(mul_ln42_15_fu_114_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U29(
    .din0(data_0_val),
    .din1(mul_ln42_fu_115_p1),
    .dout(mul_ln42_fu_115_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U30(
    .din0(mul_ln42_18_fu_117_p0),
    .din1(mul_ln42_18_fu_117_p1),
    .dout(mul_ln42_18_fu_117_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U31(
    .din0(mul_ln42_14_fu_119_p0),
    .din1(mul_ln42_14_fu_119_p1),
    .dout(mul_ln42_14_fu_119_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U32(
    .din0(data_2_val),
    .din1(mul_ln73_fu_120_p1),
    .dout(mul_ln73_fu_120_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U33(
    .din0(mul_ln42_12_fu_122_p0),
    .din1(mul_ln42_12_fu_122_p1),
    .dout(mul_ln42_12_fu_122_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U34(
    .din0(data_4_val),
    .din1(mul_ln42_16_fu_123_p1),
    .dout(mul_ln42_16_fu_123_p2)
);

assign add_ln58_15_fu_939_p2 = (trunc_ln42_18_fu_867_p4 + trunc_ln42_s_fu_786_p4);

assign add_ln58_16_fu_945_p2 = (trunc_ln42_20_fu_897_p4 + 16'd8);

assign add_ln58_17_fu_951_p2 = ($signed(trunc_ln42_22_fu_923_p4) + $signed(16'd65521));

assign add_ln58_18_fu_957_p2 = (add_ln58_17_fu_951_p2 + trunc_ln42_17_fu_857_p4);

assign add_ln58_19_fu_963_p2 = (trunc_ln_fu_769_p4 + trunc_ln42_21_fu_913_p4);

assign add_ln58_20_fu_969_p2 = (trunc_ln42_16_fu_806_p4 + trunc_ln42_19_fu_882_p4);

assign add_ln58_21_fu_975_p2 = (add_ln58_20_fu_969_p2 + 16'd10);

assign add_ln58_fu_933_p2 = ($signed(trunc_ln42_15_fu_796_p4) + $signed(16'd65529));

assign ap_ready = 1'b1;

assign sext_ln73_2_fu_829_p1 = $signed(shl_ln_fu_821_p3);

assign sext_ln73_3_fu_847_p1 = $signed(shl_ln73_1_fu_839_p3);

assign sext_ln73_4_fu_907_p1 = $signed(data_5_val);

assign sext_ln73_fu_779_p1 = $signed(data_1_val);

assign shl_ln73_1_fu_839_p3 = {{shl_ln73_1_fu_839_p1}, {5'd0}};

assign shl_ln_fu_821_p3 = {{shl_ln_fu_821_p1}, {9'd0}};

assign sub_ln73_1_fu_851_p2 = ($signed(sub_ln73_fu_833_p2) - $signed(sext_ln73_3_fu_847_p1));

assign sub_ln73_fu_833_p2 = ($signed(26'd0) - $signed(sext_ln73_2_fu_829_p1));

assign trunc_ln42_15_fu_796_p4 = {{mul_ln42_13_fu_109_p2[25:10]}};

assign trunc_ln42_16_fu_806_p4 = {{mul_ln42_14_fu_119_p2[25:10]}};

assign trunc_ln42_17_fu_857_p4 = {{sub_ln73_1_fu_851_p2[25:10]}};

assign trunc_ln42_18_fu_867_p4 = {{mul_ln73_fu_120_p2[25:10]}};

assign trunc_ln42_19_fu_882_p4 = {{mul_ln42_15_fu_114_p2[25:10]}};

assign trunc_ln42_20_fu_897_p4 = {{mul_ln42_16_fu_123_p2[25:10]}};

assign trunc_ln42_21_fu_913_p4 = {{mul_ln42_17_fu_108_p2[25:10]}};

assign trunc_ln42_22_fu_923_p4 = {{mul_ln42_18_fu_117_p2[25:10]}};

assign trunc_ln42_s_fu_786_p4 = {{mul_ln42_12_fu_122_p2[25:10]}};

assign trunc_ln_fu_769_p4 = {{mul_ln42_fu_115_p2[25:10]}};

assign ap_return_0 = add_ln58_19_fu_963_p2;

assign ap_return_1 = add_ln58_18_fu_957_p2;

assign ap_return_2 = add_ln58_15_fu_939_p2;

assign ap_return_3 = add_ln58_16_fu_945_p2;

assign ap_return_4 = add_ln58_fu_933_p2;

assign ap_return_5 = add_ln58_21_fu_975_p2;

assign mul_ln42_12_fu_122_p0 = sext_ln73_fu_779_p1;

assign mul_ln42_12_fu_122_p1 = 26'd67108337;

assign mul_ln42_13_fu_109_p0 = sext_ln73_fu_779_p1;

assign mul_ln42_13_fu_109_p1 = 26'd610;

assign mul_ln42_14_fu_119_p0 = sext_ln73_fu_779_p1;

assign mul_ln42_14_fu_119_p1 = 26'd533;

assign mul_ln42_15_fu_114_p1 = 26'd67108306;

assign mul_ln42_16_fu_123_p1 = 26'd593;

assign mul_ln42_17_fu_108_p0 = sext_ln73_4_fu_907_p1;

assign mul_ln42_17_fu_108_p1 = 26'd67108270;

assign mul_ln42_18_fu_117_p0 = sext_ln73_4_fu_907_p1;

assign mul_ln42_18_fu_117_p1 = 26'd609;

assign mul_ln42_fu_115_p1 = 26'd547;

assign mul_ln73_fu_120_p1 = 26'd67108364;

assign shl_ln73_1_fu_839_p1 = data_2_val;

assign shl_ln_fu_821_p1 = data_2_val;

endmodule //myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config6_s
