// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s (
        ap_ready,
        data_val,
        ap_return_0,
        ap_return_1,
        ap_return_2
);


output   ap_ready;
input  [31:0] data_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;

wire  signed [15:0] mul_ln42_fu_50_p0;
wire  signed [25:0] sext_ln73_fu_128_p1;
wire   [10:0] mul_ln42_fu_50_p1;
wire  signed [15:0] mul_ln42_21_fu_52_p0;
wire  signed [10:0] mul_ln42_21_fu_52_p1;
wire   [10:0] mul_ln42_22_fu_53_p1;
wire   [15:0] a_fu_124_p1;
wire   [25:0] mul_ln42_fu_50_p2;
wire   [25:0] mul_ln42_21_fu_52_p2;
wire  signed [15:0] a_1_fu_154_p4;
wire   [25:0] mul_ln42_22_fu_53_p2;
wire   [15:0] trunc_ln_fu_134_p4;
wire   [15:0] trunc_ln42_s_fu_144_p4;
wire   [15:0] trunc_ln42_27_fu_169_p4;
wire   [15:0] add_ln58_28_fu_191_p2;
wire   [15:0] add_ln58_fu_179_p2;
wire   [15:0] add_ln58_27_fu_185_p2;

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U1(
    .din0(mul_ln42_fu_50_p0),
    .din1(mul_ln42_fu_50_p1),
    .dout(mul_ln42_fu_50_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U2(
    .din0(mul_ln42_21_fu_52_p0),
    .din1(mul_ln42_21_fu_52_p1),
    .dout(mul_ln42_21_fu_52_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U3(
    .din0(a_1_fu_154_p4),
    .din1(mul_ln42_22_fu_53_p1),
    .dout(mul_ln42_22_fu_53_p2)
);

assign a_1_fu_154_p4 = {{data_val[31:16]}};

assign a_fu_124_p1 = data_val[15:0];

assign add_ln58_27_fu_185_p2 = ($signed(trunc_ln42_s_fu_144_p4) + $signed(16'd65532));

assign add_ln58_28_fu_191_p2 = ($signed(trunc_ln42_27_fu_169_p4) + $signed(16'd65524));

assign add_ln58_fu_179_p2 = (trunc_ln_fu_134_p4 + 16'd3);

assign ap_ready = 1'b1;

assign sext_ln73_fu_128_p1 = $signed(a_fu_124_p1);

assign trunc_ln42_27_fu_169_p4 = {{mul_ln42_22_fu_53_p2[25:10]}};

assign trunc_ln42_s_fu_144_p4 = {{mul_ln42_21_fu_52_p2[25:10]}};

assign trunc_ln_fu_134_p4 = {{mul_ln42_fu_50_p2[25:10]}};

assign ap_return_0 = add_ln58_28_fu_191_p2;

assign ap_return_1 = add_ln58_fu_179_p2;

assign ap_return_2 = add_ln58_27_fu_185_p2;

assign mul_ln42_21_fu_52_p0 = sext_ln73_fu_128_p1;

assign mul_ln42_21_fu_52_p1 = 26'd67108269;

assign mul_ln42_22_fu_53_p1 = 26'd787;

assign mul_ln42_fu_50_p0 = sext_ln73_fu_128_p1;

assign mul_ln42_fu_50_p1 = 26'd777;

endmodule //myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s
