// ==============================================================
// Generated by Vitis HLS v2023.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s (
        ap_ready,
        data_0_val,
        data_1_val,
        data_2_val,
        data_3_val,
        data_4_val,
        data_5_val,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6
);


output   ap_ready;
input  [15:0] data_0_val;
input  [15:0] data_1_val;
input  [15:0] data_2_val;
input  [15:0] data_3_val;
input  [15:0] data_4_val;
input  [15:0] data_5_val;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;

wire  signed [15:0] mul_ln42_11_fu_116_p0;
wire  signed [25:0] sext_ln73_1_fu_1443_p1;
wire  signed [10:0] mul_ln42_11_fu_116_p1;
wire  signed [15:0] mul_ln73_fu_117_p0;
wire  signed [25:0] sext_ln42_fu_1269_p1;
wire  signed [9:0] mul_ln73_fu_117_p1;
wire  signed [15:0] mul_ln42_6_fu_118_p0;
wire  signed [25:0] sext_ln73_fu_1369_p1;
wire  signed [10:0] mul_ln42_6_fu_118_p1;
wire  signed [15:0] mul_ln42_2_fu_119_p0;
wire  signed [25:0] sext_ln70_fu_1295_p1;
wire  signed [10:0] mul_ln42_2_fu_119_p1;
wire  signed [15:0] mul_ln42_3_fu_120_p0;
wire   [10:0] mul_ln42_3_fu_120_p1;
wire  signed [15:0] mul_ln42_fu_121_p0;
wire   [10:0] mul_ln42_fu_121_p1;
wire  signed [15:0] mul_ln73_2_fu_122_p0;
wire  signed [25:0] sext_ln42_1_fu_1343_p1;
wire  signed [9:0] mul_ln73_2_fu_122_p1;
wire  signed [15:0] mul_ln42_7_fu_123_p0;
wire  signed [25:0] sext_ln70_1_fu_1395_p1;
wire   [10:0] mul_ln42_7_fu_123_p1;
wire  signed [15:0] mul_ln42_1_fu_124_p0;
wire   [10:0] mul_ln42_1_fu_124_p1;
wire  signed [15:0] mul_ln42_5_fu_125_p0;
wire   [10:0] mul_ln42_5_fu_125_p1;
wire  signed [15:0] mul_ln73_3_fu_126_p0;
wire  signed [9:0] mul_ln73_3_fu_126_p1;
wire  signed [15:0] mul_ln42_8_fu_127_p0;
wire  signed [10:0] mul_ln42_8_fu_127_p1;
wire  signed [15:0] mul_ln42_4_fu_128_p0;
wire  signed [10:0] mul_ln42_4_fu_128_p1;
wire  signed [15:0] mul_ln42_9_fu_129_p0;
wire  signed [10:0] mul_ln42_9_fu_129_p1;
wire  signed [15:0] mul_ln42_10_fu_130_p0;
wire   [10:0] mul_ln42_10_fu_130_p1;
wire  signed [15:0] mul_ln73_1_fu_131_p0;
wire   [9:0] mul_ln73_1_fu_131_p1;
wire   [25:0] mul_ln73_fu_117_p2;
wire   [25:0] mul_ln42_fu_121_p2;
wire   [25:0] mul_ln73_1_fu_131_p2;
wire   [25:0] mul_ln42_1_fu_124_p2;
wire   [25:0] mul_ln42_2_fu_119_p2;
wire   [25:0] mul_ln42_3_fu_120_p2;
wire   [25:0] mul_ln73_2_fu_122_p2;
wire   [25:0] mul_ln42_4_fu_128_p2;
wire   [25:0] mul_ln42_5_fu_125_p2;
wire   [25:0] mul_ln42_6_fu_118_p2;
wire   [25:0] mul_ln73_3_fu_126_p2;
wire   [25:0] mul_ln42_7_fu_123_p2;
wire   [25:0] mul_ln42_8_fu_127_p2;
wire   [25:0] mul_ln42_9_fu_129_p2;
wire   [25:0] mul_ln42_10_fu_130_p2;
wire   [25:0] mul_ln42_11_fu_116_p2;
wire   [15:0] trunc_ln42_8_fu_1375_p4;
wire   [15:0] trunc_ln42_s_fu_1403_p4;
wire   [15:0] trunc_ln42_2_fu_1303_p4;
wire   [15:0] trunc_ln_fu_1275_p4;
wire   [15:0] trunc_ln42_6_fu_1349_p4;
wire   [15:0] trunc_ln42_10_fu_1413_p4;
wire   [15:0] add_ln58_3_fu_1487_p2;
wire   [15:0] add_ln58_2_fu_1481_p2;
wire   [15:0] trunc_ln42_11_fu_1423_p4;
wire   [15:0] add_ln58_5_fu_1499_p2;
wire   [15:0] trunc_ln42_1_fu_1285_p4;
wire   [15:0] trunc_ln42_4_fu_1323_p4;
wire   [15:0] trunc_ln42_7_fu_1359_p4;
wire   [15:0] trunc_ln42_12_fu_1433_p4;
wire   [15:0] add_ln58_8_fu_1517_p2;
wire   [15:0] add_ln58_7_fu_1511_p2;
wire   [15:0] trunc_ln42_3_fu_1313_p4;
wire   [15:0] trunc_ln42_9_fu_1385_p4;
wire   [15:0] trunc_ln42_13_fu_1449_p4;
wire   [15:0] add_ln58_11_fu_1535_p2;
wire   [15:0] add_ln58_10_fu_1529_p2;
wire   [15:0] trunc_ln42_14_fu_1459_p4;
wire   [15:0] add_ln58_13_fu_1547_p2;
wire   [15:0] trunc_ln42_5_fu_1333_p4;
wire   [15:0] add_ln58_1_fu_1475_p2;
wire   [15:0] add_ln58_4_fu_1493_p2;
wire   [15:0] add_ln58_6_fu_1505_p2;
wire   [15:0] add_ln58_fu_1469_p2;
wire   [15:0] add_ln58_12_fu_1541_p2;
wire   [15:0] add_ln58_9_fu_1523_p2;
wire   [15:0] add_ln58_14_fu_1553_p2;

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U47(
    .din0(mul_ln42_11_fu_116_p0),
    .din1(mul_ln42_11_fu_116_p1),
    .dout(mul_ln42_11_fu_116_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U48(
    .din0(mul_ln73_fu_117_p0),
    .din1(mul_ln73_fu_117_p1),
    .dout(mul_ln73_fu_117_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U49(
    .din0(mul_ln42_6_fu_118_p0),
    .din1(mul_ln42_6_fu_118_p1),
    .dout(mul_ln42_6_fu_118_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U50(
    .din0(mul_ln42_2_fu_119_p0),
    .din1(mul_ln42_2_fu_119_p1),
    .dout(mul_ln42_2_fu_119_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U51(
    .din0(mul_ln42_3_fu_120_p0),
    .din1(mul_ln42_3_fu_120_p1),
    .dout(mul_ln42_3_fu_120_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U52(
    .din0(mul_ln42_fu_121_p0),
    .din1(mul_ln42_fu_121_p1),
    .dout(mul_ln42_fu_121_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U53(
    .din0(mul_ln73_2_fu_122_p0),
    .din1(mul_ln73_2_fu_122_p1),
    .dout(mul_ln73_2_fu_122_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U54(
    .din0(mul_ln42_7_fu_123_p0),
    .din1(mul_ln42_7_fu_123_p1),
    .dout(mul_ln42_7_fu_123_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U55(
    .din0(mul_ln42_1_fu_124_p0),
    .din1(mul_ln42_1_fu_124_p1),
    .dout(mul_ln42_1_fu_124_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U56(
    .din0(mul_ln42_5_fu_125_p0),
    .din1(mul_ln42_5_fu_125_p1),
    .dout(mul_ln42_5_fu_125_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U57(
    .din0(mul_ln73_3_fu_126_p0),
    .din1(mul_ln73_3_fu_126_p1),
    .dout(mul_ln73_3_fu_126_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U58(
    .din0(mul_ln42_8_fu_127_p0),
    .din1(mul_ln42_8_fu_127_p1),
    .dout(mul_ln42_8_fu_127_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U59(
    .din0(mul_ln42_4_fu_128_p0),
    .din1(mul_ln42_4_fu_128_p1),
    .dout(mul_ln42_4_fu_128_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U60(
    .din0(mul_ln42_9_fu_129_p0),
    .din1(mul_ln42_9_fu_129_p1),
    .dout(mul_ln42_9_fu_129_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U61(
    .din0(mul_ln42_10_fu_130_p0),
    .din1(mul_ln42_10_fu_130_p1),
    .dout(mul_ln42_10_fu_130_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U62(
    .din0(mul_ln73_1_fu_131_p0),
    .din1(mul_ln73_1_fu_131_p1),
    .dout(mul_ln73_1_fu_131_p2)
);

assign add_ln58_10_fu_1529_p2 = (trunc_ln42_3_fu_1313_p4 + trunc_ln42_9_fu_1385_p4);

assign add_ln58_11_fu_1535_p2 = (trunc_ln42_13_fu_1449_p4 + 16'd2);

assign add_ln58_12_fu_1541_p2 = (add_ln58_11_fu_1535_p2 + add_ln58_10_fu_1529_p2);

assign add_ln58_13_fu_1547_p2 = ($signed(trunc_ln42_14_fu_1459_p4) + $signed(16'd65529));

assign add_ln58_14_fu_1553_p2 = (add_ln58_13_fu_1547_p2 + trunc_ln42_5_fu_1333_p4);

assign add_ln58_1_fu_1475_p2 = ($signed(trunc_ln42_s_fu_1403_p4) + $signed(16'd65524));

assign add_ln58_2_fu_1481_p2 = (trunc_ln42_2_fu_1303_p4 + trunc_ln_fu_1275_p4);

assign add_ln58_3_fu_1487_p2 = (trunc_ln42_6_fu_1349_p4 + trunc_ln42_10_fu_1413_p4);

assign add_ln58_4_fu_1493_p2 = (add_ln58_3_fu_1487_p2 + add_ln58_2_fu_1481_p2);

assign add_ln58_5_fu_1499_p2 = (trunc_ln42_11_fu_1423_p4 + 16'd4);

assign add_ln58_6_fu_1505_p2 = (add_ln58_5_fu_1499_p2 + trunc_ln42_1_fu_1285_p4);

assign add_ln58_7_fu_1511_p2 = (trunc_ln42_4_fu_1323_p4 + trunc_ln42_7_fu_1359_p4);

assign add_ln58_8_fu_1517_p2 = (trunc_ln42_12_fu_1433_p4 + 16'd19);

assign add_ln58_9_fu_1523_p2 = (add_ln58_8_fu_1517_p2 + add_ln58_7_fu_1511_p2);

assign add_ln58_fu_1469_p2 = (trunc_ln42_8_fu_1375_p4 + 16'd1);

assign ap_ready = 1'b1;

assign sext_ln42_1_fu_1343_p1 = $signed(data_2_val);

assign sext_ln42_fu_1269_p1 = $signed(data_0_val);

assign sext_ln70_1_fu_1395_p1 = $signed(data_4_val);

assign sext_ln70_fu_1295_p1 = $signed(data_1_val);

assign sext_ln73_1_fu_1443_p1 = $signed(data_5_val);

assign sext_ln73_fu_1369_p1 = $signed(data_3_val);

assign trunc_ln42_10_fu_1413_p4 = {{mul_ln42_7_fu_123_p2[25:10]}};

assign trunc_ln42_11_fu_1423_p4 = {{mul_ln42_8_fu_127_p2[25:10]}};

assign trunc_ln42_12_fu_1433_p4 = {{mul_ln42_9_fu_129_p2[25:10]}};

assign trunc_ln42_13_fu_1449_p4 = {{mul_ln42_10_fu_130_p2[25:10]}};

assign trunc_ln42_14_fu_1459_p4 = {{mul_ln42_11_fu_116_p2[25:10]}};

assign trunc_ln42_1_fu_1285_p4 = {{mul_ln42_fu_121_p2[25:10]}};

assign trunc_ln42_2_fu_1303_p4 = {{mul_ln73_1_fu_131_p2[25:10]}};

assign trunc_ln42_3_fu_1313_p4 = {{mul_ln42_1_fu_124_p2[25:10]}};

assign trunc_ln42_4_fu_1323_p4 = {{mul_ln42_2_fu_119_p2[25:10]}};

assign trunc_ln42_5_fu_1333_p4 = {{mul_ln42_3_fu_120_p2[25:10]}};

assign trunc_ln42_6_fu_1349_p4 = {{mul_ln73_2_fu_122_p2[25:10]}};

assign trunc_ln42_7_fu_1359_p4 = {{mul_ln42_4_fu_128_p2[25:10]}};

assign trunc_ln42_8_fu_1375_p4 = {{mul_ln42_5_fu_125_p2[25:10]}};

assign trunc_ln42_9_fu_1385_p4 = {{mul_ln42_6_fu_118_p2[25:10]}};

assign trunc_ln42_s_fu_1403_p4 = {{mul_ln73_3_fu_126_p2[25:10]}};

assign trunc_ln_fu_1275_p4 = {{mul_ln73_fu_117_p2[25:10]}};

assign ap_return_0 = add_ln58_1_fu_1475_p2;

assign ap_return_1 = add_ln58_4_fu_1493_p2;

assign ap_return_2 = add_ln58_6_fu_1505_p2;

assign ap_return_3 = add_ln58_fu_1469_p2;

assign ap_return_4 = add_ln58_12_fu_1541_p2;

assign ap_return_5 = add_ln58_9_fu_1523_p2;

assign ap_return_6 = add_ln58_14_fu_1553_p2;

assign mul_ln42_10_fu_130_p0 = sext_ln73_1_fu_1443_p1;

assign mul_ln42_10_fu_130_p1 = 26'd523;

assign mul_ln42_11_fu_116_p0 = sext_ln73_1_fu_1443_p1;

assign mul_ln42_11_fu_116_p1 = 26'd67108326;

assign mul_ln42_1_fu_124_p0 = sext_ln70_fu_1295_p1;

assign mul_ln42_1_fu_124_p1 = 26'd600;

assign mul_ln42_2_fu_119_p0 = sext_ln70_fu_1295_p1;

assign mul_ln42_2_fu_119_p1 = 26'd67108338;

assign mul_ln42_3_fu_120_p0 = sext_ln70_fu_1295_p1;

assign mul_ln42_3_fu_120_p1 = 26'd570;

assign mul_ln42_4_fu_128_p0 = sext_ln42_1_fu_1343_p1;

assign mul_ln42_4_fu_128_p1 = 26'd67108241;

assign mul_ln42_5_fu_125_p0 = sext_ln73_fu_1369_p1;

assign mul_ln42_5_fu_125_p1 = 26'd565;

assign mul_ln42_6_fu_118_p0 = sext_ln73_fu_1369_p1;

assign mul_ln42_6_fu_118_p1 = 26'd67108324;

assign mul_ln42_7_fu_123_p0 = sext_ln70_1_fu_1395_p1;

assign mul_ln42_7_fu_123_p1 = 26'd610;

assign mul_ln42_8_fu_127_p0 = sext_ln70_1_fu_1395_p1;

assign mul_ln42_8_fu_127_p1 = 26'd67108331;

assign mul_ln42_9_fu_129_p0 = sext_ln70_1_fu_1395_p1;

assign mul_ln42_9_fu_129_p1 = 26'd67108268;

assign mul_ln42_fu_121_p0 = sext_ln42_fu_1269_p1;

assign mul_ln42_fu_121_p1 = 26'd569;

assign mul_ln73_1_fu_131_p0 = sext_ln70_fu_1295_p1;

assign mul_ln73_1_fu_131_p1 = 26'd456;

assign mul_ln73_2_fu_122_p0 = sext_ln42_1_fu_1343_p1;

assign mul_ln73_2_fu_122_p1 = 26'd67108405;

assign mul_ln73_3_fu_126_p0 = sext_ln70_1_fu_1395_p1;

assign mul_ln73_3_fu_126_p1 = 26'd67108406;

assign mul_ln73_fu_117_p0 = sext_ln42_fu_1269_p1;

assign mul_ln73_fu_117_p1 = 26'd67108427;

endmodule //myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config8_s
